### ISSUE TITLE
Ignore as Flake8 option

### ISSUE THREAD

**Issue by decaz** [PyCQA/pep8-naming#102]
It would be nice to use Flake8 `ignore` configuration option to ignore errors.

**Comment by jparise** [comment]
This is already supported. Can you share what you've tried that isn't working?

**Comment by sigmavirus24** [comment]
> One more question: is it possible to use ignore-names within [flake8] options at the setup.cfg file?

Yes.

> Could you tell me when the new version will be released? Thanks!

We just did a release. I could see doing a 0.8.1 soon though if @jparise is up for it.

**Comment by jparise** [comment]
Yes, I'll plan on a 0.8.1 patch release in about a week once we wrap any remaining feedback from the 0.8.0 release.

@decaz, I'm going to close this issue. Please track #43 for extending `ignore-names` to even more error codes.

**Comment by jparise** [comment]
The 0.8.1 release i planned for Monday. (#107)
