### ISSUE TITLE
Ignore name option doesn't exclude N806

### ISSUE THREAD

**Issue by sr-murthy** [PyCQA/pep8-naming#109]
I'm running flake8 against one of my Python projects, in a Python 3.6.2 virtual env. on a Mac (OS X 10.13.6). I keep getting the error codes `N806` despite trying to ignore it

    [/path/to/my/repo]$ flake8 --ignore='E501' --ignore-names=['N806'] --count --statistics --output-file='flake8-report-03022019.txt' myproject/

I'm seeing this in the report

    ...
    myproject/somemodule.py:203:10: N806 variable 'Y' in function should be lowercase
    myproject/somemodule.py:204:10: N806 variable 'Y' in function should be lowercase
    ...

I believe that `--ignore-names` accepts a list of error codes. I also tried a string form `--ignore-names='N806'`, but this doesn't work either.

**Comment by sigmavirus24** [comment]
`--ignore=E501,N806` is what you want. `--ignore-names` ignores the names of bindings that would violate a rule, e.g., `--ignore-names=Y`.

**Comment by sigmavirus24** [comment]
See also https://github.com/PyCQA/pep8-naming#options
