### ISSUE TITLE
Metaclassfirst argument should use 'cls' for methods and 'mcs' for classmethods

### ISSUE THREAD

**Issue by penguinolog** [PyCQA/pep8-naming#114]
For normal classes is expected to use `self` and `cls` as first parameter, but metaclass is a special case:
instances of metaclasses are classes.
Expect:
```
class Meta(type):
    def __new__(mcs, ....
    def __init__(cls, ...
```

**Comment by jparise** [comment]
We agreed in #47 that all metaclass methods are class methods, and their first argument should be spelled `cls`. [Guido reached the same conclusion](https://mail.python.org/pipermail/python-dev/2018-January/151986.html).
