### ISSUE TITLE
Extend pep8-naming rules from installed libraries.

### ISSUE THREAD

**Issue by proofit404** [PyCQA/pep8-naming#117]
Hi, thanks for an awesome extension for flake8.

At [dry-python](https://github.com/dry-python) we develop libraries for pluggable business logic components.

We use DSL approach in the [stories](https://github.com/dry-python/stories) library. A tupical story looks like this:

```python
class CommentOnPost:
    """Create comment on post.  Send notifications."""

    @story
    @arguments("author", "author_type", "post_id", "text")
    def comment(I):

        I.find_post
        I.should_have_comment_permission
        I.find_community
        I.set_author_color
        I.persist_comment
        I.increase_post_comment_counter
        I.find_previous_commenters
        I.choose_recipients
        I.broadcast_new_comment_event
        I.choose_thumbnail
        I.persist_notifications
        I.send_notifications
        I.record_user_activity
        I.show_comment
```
This gives us two pep8-naming violations:
```
comment_on_post.py:36:18: N805 first argument of a method should be named 'self'
comment_on_post.py:36:18: N803 argument name 'I' should be lowercase
```
Is it possible to develop an addition to this flake8 plugin **inside** stories library to prevent argument names check if function was decorated by `@story`.

cc @asottile @sigmavirus24 

Regards, 
Artem.

**Comment by asottile** [comment]
I'm not actually involved in this project but reading the README it seems that this helps you with at least one of the errors:

```console
$ flake8 t.py --staticmethod-decorators=staticmethod,story
t.py:9:18: N803 argument name 'I' should be lowercase
```

**Comment by sigmavirus24** [comment]
Wouldn't `--ignore-names` take care of the rest of this?

**Comment by asottile** [comment]
It maybe should but doesn't seem to apply to N803
