### ISSUE TITLE
Request for release including Python 3.8 lineno fix

### ISSUE THREAD

**Issue by ericvw** [PyCQA/pep8-naming#128]
Hello!  I was wondering when the next release of `pep8-naming` will be which will include cccd2f365f6ee001086facb3c283385300de9d60 (from PR #126)?  This will enable me to update [`flake8`](https://gitlab.com/pycqa/flake8) project to lint with 3.8 as well as other projects I work on.  Thanks!

**Comment by jparise** [comment]
We just released version 0.9.0 last week, but I'll build a version 0.9.1 patch release later today or tomorrow with this additional Python 3.8 fix.

**Comment by jparise** [comment]
[Version 0.9.1](https://pypi.org/project/pep8-naming/0.9.1/) has been released.

**Comment by ericvw** [comment]
Thanks!
