### ISSUE TITLE
False positive for cls use in metaclass

### ISSUE THREAD

**Issue by dragonsinofwrath** [PyCQA/pep8-naming#136]
In a metaclass that directly inherits from type, the use of cls in `__call__` is supported and does not raise any error in the naming check:

```
class Meta(type):

    _instances = {}

    def __call__(cls):
        return super(Meta, cls).__call__()
```

When the metaclass inherits from another metaclass, however, pep8naming complains about `cls`:

```
class Meta(abc.ABCMeta):

    _instances = {}

    def __call__(cls):
        return super(Meta, cls).__call__()
```

Error message: 
```
N805 first argument of a method should be named 'self'
```

**Comment by sigmavirus24** [comment]
Welcome to GitHub @dragonsinofwrath 

I edited your comment to format properly. I'm confused about `__get__` but that's besides the point. This is coming from https://github.com/PyCQA/pep8-naming/blob/002ad939afebc8a9daf05625943b247c603b4536/src/pep8ext_naming.py#L304 but I"m confused that you're only seeing it in the second case because as far as I can tell you should be seeing it in both cases.

To help debug this further, can you please provide the output of `flake8 --bug-report`?

**Comment by dragonsinofwrath** [comment]
Yeah, sorry for the inconsistencies. Why this should throw an error? From my understanding, using self would be against convention here.
Anyway, the flake8 --bug-report output: 

`{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.6.9",
    "system": "Linux"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "naming",
      "version": "0.9.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    }
  ],
  "version": "3.7.9"
}`

Also, if you have any suggestion on how to better display the output, feel free to apply or mention it. Thanks!

**Comment by jparise** [comment]
I'll have a look at this one later today. I think there's a problem with the way I detect metaclasses. `class Meta(ABCMeta)` should work as expected, but `class Meta(abc.ABCMeta)` is failing. Probably just a minor oversight that shouldn't be hard to fix.
