### ISSUE TITLE
Explanation for N817

### ISSUE THREAD

**Issue by Dreamsorcerer** [PyCQA/pep8-naming#165]
It would be nice if the documentation gave some explanation.

`import xml.etree.ElementTree as ET`

triggers N817, yet it is the recommended format in the Python documentation.

**Comment by sigmavirus24** [comment]
https://github.com/PyCQA/pep8-naming/pull/133

It's specifically it's own error code so that it can be ignored while still implementing what's considered best practice by the community (with rare exceptions such as ET).

**Comment by Dreamsorcerer** [comment]
OK, that makes sense. Would be nice to have that info in the docs though.

**Comment by sigmavirus24** [comment]
Feel free to send a Pr to that effect.
