### ISSUE TITLE
N802 found on different lines for the same issue depending on Python version

### ISSUE THREAD

**Issue by xqt** [PyCQA/pep8-naming#168]
**pep8-naming 0.11.1** finds a N802 issue on different lines for the same issue depending on Python version:
https://integration.wikimedia.org/ci/job/pywikibot-core-tox-docker/15120/console

With Python 3.5, 3.6. and 3.7 the issue is located at line 259 but with Python 3.8 is is line 260.

The code snippet is:

    @deprecated('APISite.namespaces.lookup_name', since='20150703',
                future_warning=True)
    def getNamespaceIndex(self, namespace):
        """DEPRECATED: Return the Namespace for a given namespace name."""
        return self.namespaces.lookup_name(namespace)

and `def getNamespaceIndex(self, namespace):` is at line 260 which means that the behaviour with Python 3.8 is the right one.

**Comment by sigmavirus24** [comment]
Based on the information here, I believe this to be in how Python's `tokenize` module provides this information that Flake8 then gives to the plugin. This has been discussed in Flake8 and it's not something that can be fixed in this plugin.
