### ISSUE TITLE
False positive N805 when running against pydantic.validator

### ISSUE THREAD

**Issue by johnthagen** [PyCQA/pep8-naming#169]
Pydantic provides `classmethod` validators: https://pydantic-docs.helpmanual.io/usage/validators/

Consider the following code.

```py
from pydantic import BaseModel, validator


class DemoModel(BaseModel):
    name: str

    @validator("name")
    def check_some(cls, val: str) -> str:
        return val
```

```bash
$ pip list
Package           Version
----------------- --------
click             7.1.2
flake8            3.9.1
flake8-polyfill   1.0.2
mccabe            0.6.1
pep517            0.10.0
pep8-naming       0.11.1
pip               21.1.1
pip-tools         6.1.0
pycodestyle       2.7.0
pydantic          1.8.1
pyflakes          2.3.1
setuptools        56.0.0
toml              0.10.2
typing-extensions 3.10.0.0
wheel             0.36.2

$ flake8 --version
3.9.1 (mccabe: 0.6.1, naming: 0.11.1, pycodestyle: 2.7.0, pyflakes: 2.3.1) CPython 3.9.1 on Darwin
```

```bash
$ flake8 main.py
main.py:8:21: N805 first argument of a method should be named 'self'
```

But the definition of `validator` does properly type hint that it returns a `classmethod`.

https://github.com/samuelcolvin/pydantic/blob/5921d5ec96465c0b3ce5a3e0207843fabcd339a9/pydantic/class_validators.py#L49

```py
def validator(
    *fields: str,
    pre: bool = False,
    each_item: bool = False,
    always: bool = False,
    check_fields: bool = True,
    whole: bool = None,
    allow_reuse: bool = False,
) -> Callable[[AnyCallable], classmethod]:
```

This has been discussed a bit at: https://github.com/samuelcolvin/pydantic/issues/568

**Comment by sigmavirus24** [comment]
Pretty sure this is a flat-out "Won't Fix" from us. We don't execute any code or follow things to find their `pyi` or type stubs (in this specific case, we wouldn't import pydantic in order to determine what it returns).

**Comment by jparise** [comment]
Fortunately, there is a solution for projects that use Pydantic and pep8-naming:

```
--classmethod-decorators=classmethod,validate
```

**Comment by sigmavirus24** [comment]
I'm going to close this then since there's no work needed

**Comment by johnthagen** [comment]
The correct CLI argument is:

```
--classmethod-decorators=classmethod,validator
```

To configure within `setup.cfg` / `flake8.ini` / `tox.ini`:

```ini
[flake8]
classmethod-decorators =
    classmethod
    validator
```
