### ISSUE TITLE
Decorator pattern should not require 'self' as first parameter

### ISSUE THREAD

**Issue by cimbriano** [PyCQA/pep8-naming#21]
pep8-naming complains about the parameter of a decorator function. Take the example from this page: http://python-3-patterns-idioms-test.readthedocs.org/en/latest/PythonDecorators.html#using-functions-as-decorators

``` python
# PythonDecorators/entry_exit_function.py
def entry_exit(f):
    def new_f():
        print("Entering", f.__name__)
        f()
        print("Exited", f.__name__)
    return new_f

@entry_exit
def func1():
    print("inside func1()")

@entry_exit
def func2():
    print("inside func2()")

func1()
func2()
print(func1.__name__)
```

It (seems to be) idiomatic to call the parameter `f` or `func` or something of that nature instead of `self`

**Comment by 5j9** [comment]
I cannot reproduce this issue. Running `pep8-naming` on the code above returns no error. Is it resolved?

**Comment by cimbriano** [comment]
You are correct, this no longer reproduces.
