### ISSUE TITLE
Detect @classproperty mtehods as class methods

### ISSUE THREAD

**Issue by adamchainz** [PyCQA/pep8-naming#213]
Django’s [`classproperty`](https://docs.djangoproject.com/en/stable/ref/utils/#django.utils.functional.classproperty) decorator makes a function a class-level property, like `classmethod` plus `property`.

It would be nice if rules N804 and N805 treated `classproperty` decorated functions as class methods.

**Comment by sigmavirus24** [comment]
Why not add it to `--classmethod-decorators` in your config? Adding Django specific names seems like a recipe for false negatives

**Comment by adamchainz** [comment]
Apologies, I missed that setting, yes will add there.

**Comment by sigmavirus24** [comment]
No worries. I was worried something there wasn't working or sustainable
