### ISSUE TITLE
ignore-names globbing is not case-sensitive on Windows

### ISSUE THREAD

**Issue by malsyned** [PyCQA/pep8-naming#218]
--ignore-names uses `fnmatch.fnmatch` to handle globbing when matching identifiers against its arguments. However, `fnmatch.fnmatch()` is intended to be used on filenames, and is case-insensitive on Windows but case-sensitive on Linux and MacOS. To get consistent case-sensitive matching on all platforms, `fnmatch.fnmatchcase()` is a better choice.

# Input file `pep8_naming_glob_bug.py`
```python
class Ignore_This:
    pass


class do_not_ignore_this:
    pass
```

# Output on Linux
```sh
$ flake8 --ignore-names '*Ignore*'; echo $?
./pep8_naming_glob_bug.py:5:8: N801 class name 'do_not_ignore_this' should use CapWords convention
1
```

# Output on Windows
```sh
$ flake8 --ignore-names '*Ignore*'; echo $?
0
```

**Comment by jparise** [comment]
Fixed by #219
