### ISSUE TITLE
Rename/Rebrand

### ISSUE THREAD

**Issue by sigmavirus24** [PyCQA/pep8-naming#23]
@gvanrossum requested that pep8 and pep257 rename themselves to avoid confusion. This flake8 plugin is far less popular, but I suspect we should rename ourselves too.

Thoughts? /cc @Nurdok @IanLee1521

**Comment by IanLee1521** [comment]
Having not really used this directly, and just quickly skimming the readme, what about something like "flake8-naming" ? That is generic and also seems to match the version output when installed where you just refer to it as "naming: 0.2" under flake8 versions:

    $ flake8 --version
    2.0 (pep8: 1.4.3, pyflakes: 0.6.1, naming: 0.2)

**Comment by sigmavirus24** [comment]
For some context, @florentx created this because he was receiving a lot of requests to implement checks that enforce PEP-0008's suggested naming style. It's incomplete. 

I don't like the name flake8-naming but that does kind of follow suit with flake8-docstrings (and flake8-import-order, etc., etc., etc.).

I think I'll rename this after some time. I have other things that are higher priority for me right now.

**Comment by Nurdok** [comment]
`pynamestyle`? :)

**Comment by sigmavirus24** [comment]
On February 5, 2016 6:56:20 PM CST, Amir Rachum <notifications@github.com> wrote:
>`pynamestyle`? :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PyCQA/pep8-naming/issues/23#issuecomment-180639818

Unlike pycodestyle and pydocstyle, this isn't a stand alone tool. This is a plugin for flake8
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sigmavirus24** [comment]
Eh, I don't care enough to bother renaming it.
