### ISSUE TITLE
autopep8 plugin

### ISSUE THREAD

**Issue by spaceone** [PyCQA/pep8-naming#33]
It would be nice if there would be a plugin for https://github.com/hhatto/autopep8 to fix variable and function names from camelCase to lower_underscore_case. autoflake8 has multiple aggressive modes.

**Comment by sigmavirus24** [comment]
There is no way to plug into autopep8.

**Comment by spaceone** [comment]
There is:
https://github.com/hhatto/autopep8/blob/master/autopep8.py#L29

You just need to add a function named "fix_N123" into the autopep8 module namespace.
