### ISSUE TITLE
Create setting to warn if function and method names are not mixedCase

### ISSUE THREAD

**Issue by advance512** [PyCQA/pep8-naming#36]
As explained here:
https://www.python.org/dev/peps/pep-0008/#function-names
("mixedCase is allowed only in contexts where that's already the prevailing style (e.g. threading.py), to retain backwards compatibility.")

In some contexts, mixedCase is allowed. For such cases, create a setting to allow pep8-naming to by-default check that function/method names are in mixedCase instead of snake_case.

**Comment by sigmavirus24** [comment]
Would you like to contribute this feature?

**Comment by advance512** [comment]
Sure. I'll probably only get to it in two to three weeks, but it is definitely something I need and looking at the code - doesn't seem hard to do. Any guidelines?

**Comment by ArneBachmann** [comment]
This is something I would also need, as I mainly use camelCase for function/method names. A configuration setting is needed to switch the behavior of N803, which is very restrictive and ugly, e.g.

```python
getNextBackupName
get_next_backup_name
```

Using the underscore breaks my typing flow, and why sacrifice 26 perfectly good upper case characters in favor of even longer function names?

**Comment by sigmavirus24** [comment]
Given PEP-8's recommendation is snake case, I'd recommend breaking this out into its own plugin at this point. More flags, etc. don't make this particular code-base easier to maintain
