### ISSUE TITLE
Config to allow decorators that function like @classmethod

### ISSUE THREAD

**Issue by saifelse** [PyCQA/pep8-naming#38]
In SQLAlchemy, there is a `declared_attr` decorator that creates class methods:
http://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/api.html#sqlalchemy.ext.declarative.declared_attr

As a result, my codebase is sprinkled with:
```
class SomeTable(db.Model):
    @declared_attr
    def __table_args__(cls):  # noqa: N805
        ...
```

It would be nice if we could have a config option that lets us declare if a decorator results in a `staticmethod` or `classmethod` as opposed to the implicit default of it being an instance method. I was thinking something like using comma separated list in the setup.cfg/tox.ini file, e.g:

```
[flake8]
classmethod-decorators=declared_attr
staticmethod-decorators=staticdeco1,staticdeco2
```

**Comment by sigmavirus24** [comment]
This certainly seems reasonable

**Comment by saifelse** [comment]
@sigmavirus24: do you have any suggestions for testing such a change? I have a working implementation, but the testing framework does not allow custom options to be passed into the NamingChecker.

I'm currently experimenting with the test syntax looking as such:
```
#: Okay(--staticmethods=exstatik,stcmthd)
class SecondNewStatic(object):
    @stcmthd()
    def test(so, exciting):
        pass
```

and then parsing the options, which get passed to an instance of `flake8.options.manager.OptionManager` in ./run_tests.py.

Does this sound like an OK approach to you?

Also, looking at the codebase, I'm unsure which version of flake8 I am using within the test suite. Is it always the latest version?

**Comment by saifelse** [comment]
@sigmavirus24: just checking to see if there is anything else I need to do on my end to get #39 through. Cheers!
