### ISSUE TITLE
Allow methods starting with "assert"

### ISSUE THREAD

**Issue by treyhunner** [PyCQA/pep8-naming#40]
When using `unittest`, I tend to name custom assertion methods using camelCase.

I tried setting `ignore-names` to include `assert*` but that didn't do what I'd hoped. If there was a way to specify a glob or regular expression in `ignore-names`, that would allow me to accept all methods starting with `assert` as valid.

**Comment by jparise** [comment]
Closing this in favor of #82, which proposes a possible solution (supporting globs in `ignore-names`).
