### ISSUE TITLE
N802 message ends with superfluous xxx

### ISSUE THREAD

**Issue by lordmauve** [PyCQA/pep8-naming#58]
The N802 error has 'xxx' on the end. Debugging?

This is [in the source, here](https://github.com/PyCQA/pep8-naming/blob/8e6694369d3c76f5f45a98c643bc52f32336b8ca/src/pep8ext_naming.py#L243):

```
N802 = "function name '{name}' should be lowercase xxx"
```

**Comment by sigmavirus24** [comment]
*shrug* Seems likely. I'm happy to merge a PR that drops this though.
