### ISSUE TITLE
plugin for pytest

### ISSUE THREAD

**Issue by OmriTreidel** [PyCQA/pep8-naming#76]
It would be great to have a pytest plugin in order to run it as part of the unittests

`py.test --pep8-naming`

**Comment by sigmavirus24** [comment]
pep8-naming is a *flake8 plugin* which means the pytest plugin would need to run flake8. If you have that and you install pep8-naming then you should run pep8-naming at the same time. :tada:

**Comment by svenevs** [comment]
@OmriTreidel just to clarify if you are getting started with all of this stuff / are confused (as I very much was), to expand on what @sigmavirus24 means is that there are two separate "tests" here.  `py.test` is for running your code "unit tests", whereas `flake8` (and by extension `pep8-naming`) is for running "lint tests", for which `pep8-naming` is specifically linting the naming of classes / variables.

I'll link you to my project's setup using `tox`, when invoking these kinds of tests they are two separate "environments" (a `tox` idea).  So in my continuous integration, running the python "unit tests" is done with `tox -e py`, whereas running the "linting tests" is done with `tox -e flake8`.  To get `pep8-naming` in as part of the larger suite of `flake8` linting tests, you simply install the `pep8-naming` _flake8 plugin_ in addition to any other plugins you want: https://github.com/svenevs/exhale/blob/17ecbd9573efe70e59fabc73b66ca544fb24d310/tox.ini#L14-L25

You do not have to use `tox` to accomplish this (though it is swimmingly convenient).  All that is required to have the `pep8-naming` tests run when you execute `flake8` is to install both `flake8` and `pep8-naming`.  You can run `flake8 --version` to see what _plugins_ you have installed / will currently be run, noting that if you want to get rid of any plugins you must uninstall them.  (Side note, `tox` creates a new `virtualenv` for each "environment", which makes enabling / disabling _flake8 plugins_ very convenient without altering the behavior of your "system" `flake8`).

I hope that clears things up!

**Comment by sigmavirus24** [comment]
@svenevs and to be clear, there are other things like plugins to pytest for running pyflakes as part of your tests so you don't have to run it separately. So that's not unusual. The only problem is trying to make this flake8-plugin work directly with pytest :)

**Comment by svenevs** [comment]
Oh hey I never even considered this!  There seems to by a [`pytest-flak8` plugin already](https://github.com/tholo/pytest-flake8), which explicitly notes

> If optional flake8 plugins are installed, those will be used automatically. No provisions have been made for configuring these via pytest.

Very interesting.  Sorry for adding noise to this, the world of python testing is vast and magnificent :upside_down_face:

**Comment by sigmavirus24** [comment]
> Oh hey I never even considered this!

Yeah, it's not my preferred method either, but I understand why folks do it. 

> Very interesting. Sorry for adding noise to this, the world of python testing is vast and magnificent 🙃

That it is 😄
