### ISSUE TITLE
Loop variables not detected

### ISSUE THREAD

**Issue by jauerb** [PyCQA/pep8-naming#79]
```
def test(values):
    """Test naming conventions."""
    for myValue in values:
        print(myValue)
```

Does not create any warnings, but 

```
def test(values):
    """Test namining conventions."""
    myValue = None
    for myValue in values:
        print(myValue)
```
results in 

> test.py:6:5: N806 variable 'myValue' in function should be lowercase

**Comment by 5j9** [comment]
The version on PYPI is outdated, try the master. (fixed in https://github.com/PyCQA/pep8-naming/commit/7ff99364ffe019468af2baa7b2e54f07022428ab)

**Comment by sigmavirus24** [comment]
@5j9 perhaps we should put together a release?

**Comment by jauerb** [comment]
Confirmed this is resolved on master.
