### ISSUE TITLE
Support `async` functions and method

### ISSUE THREAD

**Issue by sobolevn** [PyCQA/pep8-naming#80]
Currently this extensions does not support `AsyncFunctionDef`.
And does not check anything in it unlike in normal `FunctionDef`.

I guess this should be addressed, since many people use `async` and it is a part of the language.

**Comment by sigmavirus24** [comment]
Is this still true on master or only on the version of PyPI?

I know changes have been made since the last release. It may be that we just need to release them. Otherwise, it would make sense to support the `async`-related keywords

**Comment by sobolevn** [comment]
`master` do not contain a single `async` word as I can tell.
https://github.com/PyCQA/pep8-naming/blob/master/src/pep8ext_naming.py

**Comment by sobolevn** [comment]
@sigmavirus24 @5j9 thanks for implementing this! Very useful improvement. 
What's your releasing pipeline? When the next release is planned? Anything I can help with?

Waiting for it to close [this issue](https://github.com/wemake-services/wemake-python-styleguide/issues/308) of mine.

Cheers!

**Comment by sobolevn** [comment]
@sigmavirus24 Sorry for bothering you, but I really hope to see a new release.
The last one was half an year ago. Since that time a lot of bugs were fixed, including this one.

Is there anything that is blocking the process? If so, please let me help you.
