### ISSUE TITLE
Support regexps (or at least globs) on --ignore-names

### ISSUE THREAD

**Issue by ramnes** [PyCQA/pep8-naming#82]
Being able to give regexps (or at least globs) to --ignore-names would be very handy. :slightly_smiling_face: 

For example, here: https://github.com/ramnes/qtile/commit/182a92dd0eb5614b012a6ab90e8d313953ee9670

**Comment by sigmavirus24** [comment]
I think `globs` would make sense. To be clear, you're thinking you'd like to use `--ignore-names handle_*` right?

**Comment by ramnes** [comment]
Exactly. :+1:
