### ISSUE TITLE
Allow namespaces to be uppercase

### ISSUE THREAD

**Issue by snoack** [PyCQA/pep8-naming#90]
In one of our projects, we use classes to emulate namespaces for constants, e.g.:

```python
class CONTENT_TYPES:
    TEXT = 1
    IMAGE = 2
    MEDIA = 3
```

Would you be open to relax `N801` allowing class names to be in all uppercase (or at least if the class doesn't have any methods)?

**Comment by lordmauve** [comment]
No, this is not conventional. As a citation, the examples given in the [enum documentation](https://docs.python.org/3/library/enum.html) are spelled like `Color.RED`.
