### ISSUE TITLE
TestCase attributes trigger N815

### ISSUE THREAD

**Issue by jaap3** [PyCQA/pep8-naming#93]
With the recent release of `pep-8-naming` I suddenly get `N815` warnings for the `maxDiff` attribute on `unittest.TestCase`s (https://docs.python.org/3/library/unittest.html#unittest.TestCase.maxDiff)

I haven't verified this, but I assume other `TestCase` attributes will also trigger this (i.e. 
`failureException` (https://docs.python.org/3/library/unittest.html#unittest.TestCase.failureException), `longMessage` (https://docs.python.org/3/library/unittest.html#unittest.TestCase.longMessage))

**Comment by jparise** [comment]
N815 (mixedCased variable names at class scope) and N816 (mixedCased variable names at global scope) are new error codes in the 0.8.0 release. You can [disable](http://flake8.pycqa.org/en/latest/user/violations.html) them to get the previous pep8-naming behavior.

I agree that they're pretty noisy on a code base that uses `unittest`. I think we should ignore those well-known stdlib symbols by default, perhaps by honoring the `ignore-names` list when checking for N815/N816. (Currently, `ignore-names` is only used by N802 errors.)

**Comment by jparise** [comment]
#43 is somewhat related, too.

**Comment by jaap3** [comment]
Thanks for the quick fixes 👍
